[package]
name = "steam-workshop-downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
steamworks = "0.9.0"
regex = "1.5.6"
lazy_static = "1.4.0"